version: '3.8'
services:
  rabbit:
    image: "rabbitmq"
    container_name: rabbit
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    ports:
    - "5671:5671"
    - "5672:5672"
    - "15671:15671"
    - "15672:15672"
    - "15675:15675"
    - "15692:15692"
    - "1883:1883"
    - "8883:8883"
    volumes:
    - "./rabbit_enabled_plugins:/etc/rabbitmq/enabled_plugins"
    - "./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro"
