stateDiagram-v2
    direction LR
    [*] --> closed
    closed --> available: open
    available --> busy_pickup: assign_pickup_truck
    available --> busy_dropoff: assign_dropoff_truck
    busy_pickup --> available: complete_service
    busy_dropoff --> available: complete_service
    available --> closed: close

    closed --> out_of_service: breakdown
    available --> out_of_service: breakdown
    busy_pickup --> out_of_service: breakdown
    busy_dropoff --> out_of_service: breakdown
    out_of_service --> closed: repair
