from statemachine import State, StateMachine

class HaulTripStateMachine(StateMachine):
    created = State('Created', initial=True)
    assigned = State('Assigned')
    en_route_to_pickup = State('En Route to Pickup')
    waiting_at_pickup = State('Waiting at Pickup')
    at_pickup_gate = State('At Pickup Gate')
    loading = State('Loading')
    loaded = State('Loaded')
    en_route_to_dropoff = State('En Route to Dropoff')
    waiting_at_dropoff = State('Waiting at Dropoff')
    at_dropoff_gate = State('At Dropoff Gate')
    unloading = State('Unloading')
    completed = State('Completed', final=True)
    cancelled = State('Cancelled', final=True)

    assign = created.to(assigned)
    start_trip_to_pickup = assigned.to(en_route_to_pickup)
    arrive_at_pickup = en_route_to_pickup.to(waiting_at_pickup)
    enter_pickup_gate = waiting_at_pickup.to(at_pickup_gate)
    start_loading = at_pickup_gate.to(loading)
    finish_loading = loading.to(loaded)
    start_trip_to_dropoff = loaded.to(en_route_to_dropoff)
    arrive_at_dropoff = en_route_to_dropoff.to(waiting_at_dropoff)
    enter_dropoff_gate = waiting_at_dropoff.to(at_dropoff_gate)
    start_unloading = at_dropoff_gate.to(unloading)
    finish_unloading = unloading.to(completed)
    cancel = (created | assigned | en_route_to_pickup | waiting_at_pickup | at_pickup_gate | loading | loaded | en_route_to_dropoff | waiting_at_dropoff | at_dropoff_gate | unloading).to(cancelled)
